### ISSUE TITLE
Presence validation always fails with ActiveAdmin

### ISSUE THREAD

**Issue by abhimediratta** [mspanc/just-datetime-picker#13]
I'm doing as said in the Readme doc, but still it isnt working as it is supposed to be working.
On submit it always shows the datetime field to be blank.

ActiveAdmin => 'master' branch

**Comment by ggrillone** [comment]
I am having the same issue. I compared the form params passed to the controller with and without the `datetimepicker` enabled and they are identical. Not sure exactly if the issue is on the active admin side or with this gem. 

Rails: 4.0.8
Active admin version: 1.0.0.pre

Form params without just-datetime-picker:

````
message[expires_at_date]:2015-01-21
message[expires_at_time_hour]:00
message[expires_at_time_minute]:00
`````

Form params WITH just-datetime-picker:

````
message[expires_at_date]:2015-01-31
message[expmessageires_at_time_hour]:00
message[expires_at_time_minute]:00
`````

**Comment by ggrillone** [comment]
I cloned the repo and I believe I resolved the issue. I applied the changes to the application I am working on and all the fields saved properly. If you give me permissions I can push my local changes for a PR review. (they are in a new branch)

Essentially what I did is added hidden fields to the `formtastic-input.rb` file. I split the `date` into 3 separate fields so the form names could be named properly for active admin. Then I created a new js file, which has change listeners that will update the hidden field values everytime the datepicker or hour/minute fields change.
